### ISSUE TITLE
Word clouds don't match with query results

### ISSUE THREAD

**Issue by PimHuijnen** [UUDigitalHumanitieslab/texcavator#100] opened 2016-03-03 08:39 UTC
Perhaps this is an older issue, but I came across it again the other day: I've saved a query of about 900 documents and try to generate a word cloud from it. The progress bar, however, shows me that it generates a word cloud of only 681 documents. See screenshot. How is this possible?

<img width="1680" alt="screen shot 2016-02-22 at 13 45 17" src="https://cloud.githubusercontent.com/assets/7008958/13488732/4ded0812-e123-11e5-9f45-80e198757a44.png">

**Comment by jgonggrijp** [comment] 2016-03-08 10:21
Just to be sure that the problem is in the word cloud: what is the shown document count when you press the fetch button (yellow torch) on this saved query?

**Comment by PimHuijnen** [comment] 2016-03-08 10:53
I couldn't tell you. When I press the button now, it returns 1378 documents - the same amount as is used to generate the word cloud. (It still says 903 in the saved queries list, though).

**Comment by jgonggrijp** [comment] 2016-03-09 09:54
There have been changes in the index which may cause the same query to return a different number of results. Since we cache the number of results, this number is not automatically updated in your query list. This almost certainly explains the discrepancy between 903 and 1378. I suspect this was also causing the earlier discrepancy between 903 and 681.

If you want, you can manually refresh the number on a per-query basis by first fetching the results, then pressing the modify button (diskette icon) without actually modifying anything about the query. If the number update is not visible, refresh the query list. We (the developers) should probably look into updating these numbers automatically when the index changes.

I will now close this ticket for now, on the assumption that it is just a side effect of result number caching. However, if you find a discrepancy between search results and word cloud document count again, please feel free to reopen it.

**Closed by jgonggrijp** 2016-03-09 09:54 UTC
Labels: bug, word clouds
